import Vue from 'vue'         // give me access to all the Vue facilities 
import App from './App.vue'   // give me access to everything in App.vue

Vue.config.productionTip = false // optional - turn off the tool tip feature of Vue

new Vue({                        // Give me a new Vue object
  render: h => h(App),           // Insert the code generated by App.vue into the <div> with the id='app' in the index HTML
}).$mount('#app')                
